// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvxEuPBpnYBntwPSXgYfTzBB_7McltZzQ',
    appId: '1:779274727569:web:87a178c2de688ba78c8f30',
    messagingSenderId: '779274727569',
    projectId: 'globetrek-67056',
    authDomain: 'globetrek-67056.firebaseapp.com',
    storageBucket: 'globetrek-67056.firebasestorage.app',
    measurementId: 'G-192ET6VEE0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByY89mVzZuJj6kDWs0cR_uBkxgs5-WaVM',
    appId: '1:779274727569:android:4bb5269066b4aefd8c8f30',
    messagingSenderId: '779274727569',
    projectId: 'globetrek-67056',
    storageBucket: 'globetrek-67056.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5Sy6hJpFwFnJB3vHtII8U4rq5GLxCqDA',
    appId: '1:779274727569:ios:5be5c37f611731f98c8f30',
    messagingSenderId: '779274727569',
    projectId: 'globetrek-67056',
    storageBucket: 'globetrek-67056.firebasestorage.app',
    iosBundleId: 'com.example.globeTrek',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5Sy6hJpFwFnJB3vHtII8U4rq5GLxCqDA',
    appId: '1:779274727569:ios:5be5c37f611731f98c8f30',
    messagingSenderId: '779274727569',
    projectId: 'globetrek-67056',
    storageBucket: 'globetrek-67056.firebasestorage.app',
    iosBundleId: 'com.example.globeTrek',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvxEuPBpnYBntwPSXgYfTzBB_7McltZzQ',
    appId: '1:779274727569:web:fa4cbdf789e03b268c8f30',
    messagingSenderId: '779274727569',
    projectId: 'globetrek-67056',
    authDomain: 'globetrek-67056.firebaseapp.com',
    storageBucket: 'globetrek-67056.firebasestorage.app',
    measurementId: 'G-XCBTTZJ1GZ',
  );
}
